export default {
  "tips": [
    "Focus on positive things you can feel in the moment. For example, the warmth of the sun or a pleasantly cool breeze.",
    "It's healthy to question your beliefs and assumptions. Remember your perspective is limited, and there's always more information out there.",
    "Be open and curious.",
    "If you get stressed out, do something tangible to change your state of mind. A few ideas, you could wash the dishes, organize your desk, or fix something broken.",
    "When you experience anger, bring awareness to your breath.",
    "Heighten your awareness to give yourself focus and energy today.",
    "Know that you're capable of living with awareness.",
    "Acknowledge that your thoughts and emotions don't define you.",
    "Focus on your breath when you're feeling an intense emotion. Breathing can reset your state of mind.",
    "Try to single-task, not multi-task. For example, when you're brushing your teeth, just brush your teeth. Don't miss out on an experience by trying to make it three experiences.",
    "Spend at least 5 minutes a day doing nothing. Just sit in silence. Become comfortable with stillness.",
    "When you're chatting with your friends, be present.",
    "Try to focus inwards before looking outwards.",
    "You shouldn't trust every thought that comes into your head.",
    "Pay attention to the present moment with your body and mind. Stay curious and kind.",
    "Try to notice one new thing today.",
    "Try to observe the thoughts and emotions in your head without letting them carry you away.",
    "Try to be fully present and deeply engaged when talking to one person today.",
    "Be a spectator of what goes on in your mind.",
    "Remember to get off autopilot and be present today.",
    "Try to be more aware of your thoughts, emotions, and sensations without being reactive and judgmental towards them.",
    "Develop your capacity to notice and enjoy the pleasant moments in your life.",
    "When you wake up, stay in bed for a minute and stretch your body, noticing all the physical sensations of being alive.",
    "As you walk to your destination, be aware of your surroundings and the feeling of your feet touching the ground.",
    "Take a breath before and after every meeting in your work day.",
    "Pause for a second before you respond to an email you've received. Do the same thing before you hit 'send' on one you've written.",
    "Before you say something, consider three things. 1. Is it true? 2. Is it kind? 3. Is it necessary?",
    "Before you walk into your home, pause and take a breath.",
    "Observe the present moment. Ask yourself, what do you see, hear, and feel?",
    "When you feel stressed, tell yourself, I'm strong, capable, and loveable. Repeat it throughout the day as needed.",
    "Try doing one small act of kindness today.",
    "Say one nice thing to a friend, family member, or acquaintance.",
    "Cultivate a more unconditional kindness towards yourself and others.",
    "Keep your mind peaceful by focusing on generosity and warm-heartedness.",
    "When you're waiting in a long line at the grocery store, wish happiness to the other people in line with you.",
    "Whenever you meet someone new, think to yourself: I want this person to be happy. –Chade-Meng Tan",
    "Whenever you are about to find fault with someone, ask yourself the following question. What fault of mine most closely resembles the one I'm about to criticize? –Marcus Aurelius ",
    "Breathing deeply calms the nervous system. Start by placing your hand an inch below your belly button, then relaxing as you take a slow, deep inhale and focusing on the feeling of your abdomen expanding and contracting.",
    "Inhale deeply, then tighten as many muscles as you can in your body, and hold for 3 seconds. Slowly exhale while relaxing your muscles, then repeat.",
    "The hard part about being mindful is creating a routine for mindful practices and sticking to it.",
    "Remember that mindful breathing can increase your awareness and reduce your tendency to dwell on things.",
    "Take a moment to pay attention to the present moment, and notice what arises without judgement.",
    "When someone is talking to you, try to give them your undivided attention.",
    "Try to be mindful in every second of your life, not just when you meditate.",
    "You don't need acceptance from others, just acceptance from your own heart.",
    "You have to love yourself before you can love anyone else. If you accept yourself for who you are, you'll make people happy just by being around them.",
    "You're worthy. You're definitely good enough. Believe that in your heart.",
    "You can find the ability to achieve your goals by finding the time first. Start by carving out an hour or so on your calendar.",
    "Make a list of the top 5 things in life that bring you joy.",
    "Take a deep breath every time you use your phone.",
    "Don't forget to simply be and the joy that comes with it.",
    "When you experience an unpleasant emotion, ask yourself, is it useful for me to continue this anger or fear or whatever you're feeling?",
    "When you experience an unpleasant emotion, remember you have the power to change the situation. Then accept the choice you've made.",
    "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it. And this you have the power to revoke at any moment. –Marcus Aurelius",
    "A space exists between stimulus and response. In that space lies our power to choose, and in our choice lies growth and freedom.",
    "Research shows that making an oath to perform a behavior increases the likelihood you'll follow through. So make a vow to practice gratitude. It can be as simple as writing a note to yourself that says \"Count your blessings\".",
    "Think of 3 things that went well for you today, and why they went well.",
    "Think about 3 people you're grateful to have in your life.",
    "Ask yourself what you're grateful for today.",
    "Avoid comparing yourself to other people. Be thankful you are who you are.",
    "Try to live every second with unconditional love.",
    "Are you happy? If not, take the risk of being happy.",
    "Bring joy to one person today. Think about the kind of joy you can offer.",
    "Be positive, and more positivity will come to you.",
    "When you observe an unpleasant moment, try to see it as a growth opportunity instead of suffering.",
    "Don't dwell on the past so much that you miss the opportunities right in front of you.",
    "If the world is getting you down, remember that truth and love have always won throughout history. Never forget that good can prevail.",
    "Think about your head, how does it feel? Think about your hands, how do they feel? Think about your breath, how smooth is it? Congratulations, you just practiced mindfulness.",
    "Spend more time thinking about what you did accomplish than what you didn't.",
    "The things that bring you the most energy are probably your greatest strengths. Why not live in a way that celebrates them?",
    "Slow down for 3 minutes to take in your surroundings and recognize something interesting or beautiful nearby. Pausing in your routine can reset your whole state of mind.",
    "If you're acting out of habit and not desire, stop and think for a second before you make your next move.",
    "If someone isn't hearing what you have to stay, stop and listen to them before you get mad. Maybe they need someone to hear them, too.",
    "Give what you want to receive. Your generosity will rebound to you in happiness.",
    "Telling the truth is the path to a clearer mind.",
    "Make a plan for how you'll attain your goals. Be as specific as possible, even write down a checklist of action items.",
    "Don't wait for happiness to come to you. Walk towards it with open arms.",
    "Surround yourself with happy people. Good moods are contagious.",
    "Observe the space between your thoughts and then observe the observer. –Hamilton Boudreaux ",
    "Learn to let go of the past and take the lessons with you.",
    "Plan for the future instead of worrying about the future. But don't expect it'll necessarily go as you planned.",
    "Remember that everybody wants to feel heard and understood.",
    "Set your intention for the day. For example, decide to be focused, creative, or caring.",
    "Ask yourself, are you present or on autopilot? Are you being intentional, or reactive?",
    "Make someone feel heard and appreciated today.",
    "Try to separate fact from judgment. Ask yourself, are my thoughts really true?",
    "Take a breath before sending a message or an email.",
    "Begin each meal with 3 mindful bites.",
    "In each conversation, make an effort to notice the underlying feeling or emotion.",
    "You can't control the fact that you'll always be surrounded by stimuli. But you can control your response.",
    "Try to recall 5 positive things for every negative thing you experience.",
    "Remember, you control your actions and attitude.",
    "Build your mindfulness muscle with practices like mindful breathing, walking, eating, and drinking.",
    "Extend a moment of gratitude for all the work that's going on in your body, supporting you and giving you life.",
    "Extend a moment of gratitude whenever you become aware of your mind wandering, and are able to renew your focus.",
    "Take a few minutes today to write down 5 things you're grateful for.",
    "The next time you see someone new, remember, this person wishes to be happy, safe, healthy, and loved, just like me.",
    "Each time you meet someone new, think to yourself, this person has feelings, emotions, and thoughts, just like me.",
    "When you sit in your chair today, sense your feet and hands. Allow your spine to lengthen.",
    "Remember that you always have more than one choice, and the ability to choose from them.",
    "Notice when you or others smile today. How do you feel?",
    "Inhale love, peace, and joy with each breath you take.",
    "If I have the belief that I can do it, I shall surely acquire the capacity to do it even if I may not have it at the beginning. –Mahatma Gandhi",
    "Think of a goal you hope to accomplish in a month's time. Then, mindfully create a plan that enables you to work towards that goal.",
    "Remember that healthy levels of good stress can inspire innovation and even energize you.",
    "Write a thank you letter to your family member, friend, colleague, or even a stranger.",
    "The inspiration you seek is already within you. Be silent and listen. –Rumi",
    "For your next meal, try to eat mindfully. Put down your utensil between bites.",
    "It's normal to feel bored sometimes. Your mind needs to be still for you to have new ideas.",
    "When eating a meal, enjoy every bite.",
    "Before you eat, thank the people who prepared the meal including the ingredients and thank the people you're about to enjoy the meal with.",
    "Before you start eating, reflect on how you feel, and recognize the difference between what you want and what you need. Then decide if, what, and how you want to eat.",
    "Remember that being mindful can help you act from the heart.",
    "If you forget to practice mindfulness today, don't beat yourself up. Forgive yourself.",
    "In a week's time, reflect on your practice of mindfulness. Are you experiencing breathtaking impact?"
  ]
};
